"""Walk-forward analysis: select on the past, evaluate on what follows.

Implements backtesting.md §3's walk-forward row and anti-overfitting
§2.3: rolling (or expanding) windows, candidates re-selected inside
each window's training slice, results aggregated across the windows'
out-of-sample segments — a single in-sample fit is never the headline.

Construction, stated so a reader cannot mistake it for anything else:

- Windows are generated by bar position on the pinned dataset:
  ``train`` bars of selection data followed immediately by ``test``
  bars of evaluation data, advancing ``step`` bars at a time
  (``expanding=True`` grows the training slice from bar 0 instead of
  rolling it). Test bars always start strictly after their own
  window's training bars — no look-ahead within a window.
- Each window is an **independent simulation**: fresh capital, fresh
  strategy instance, fresh risk evaluator; no position or ledger
  state carries between segments.
- Later windows' training slices **do contain** earlier windows'
  test segments — they are past data by then. This is the standard
  walk-forward construction, recorded in the summary's notes so it
  can never be read as one global hold-out. The held-out-once
  protocol lives in :mod:`~harsh_quant_os.backtesting.validation`.
- The out-of-sample track **compounds** each segment's net return as
  if the full capital were re-deployed at each segment start; pooled
  trade counts are summed across segments. Every per-window number is
  kept beside the aggregate — the surface, not the optimum
  (anti-overfitting §2.4).

Every run — each candidate on each training slice, each selected
strategy on each test slice — carries its own §3 manifest inside the
summary, so the whole analysis is replayable from stored JSON
(:meth:`WalkForwardSummary.to_json` / :func:`WalkForwardSummary.
from_json`), which refuses tampered or structurally inconsistent
summaries before they can be believed.
"""

from __future__ import annotations

import json
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import cast

from harsh_quant_os.backtesting.data import BacktestData
from harsh_quant_os.backtesting.engine import BacktestConfig, BacktestResult, run_backtest
from harsh_quant_os.backtesting.errors import BacktestError
from harsh_quant_os.backtesting.manifest import build_manifest, compute_run_id, run_from_manifest
from harsh_quant_os.backtesting.report import wilson_interval
from harsh_quant_os.backtesting.validation import (
    ENDING_EQUITY,
    Candidate,
    CandidateRun,
    OutOfSampleNumbers,
    SelectionObjective,
    SelectionTrace,
    select_on_train,
)
from harsh_quant_os.safety.risk import RiskEvaluator

__all__ = [
    "SUMMARY_VERSION",
    "OosTrack",
    "WalkForwardSummary",
    "WalkForwardWindow",
    "WindowOutcome",
    "replay_walk_forward",
    "walk_forward",
    "walk_forward_windows",
]

#: Layout version of the stored summary JSON. A different layout is
#: refused rather than guessed at (manifest.py's rule, applied here).
SUMMARY_VERSION = 1

#: The honesty notes that ride inside every stored summary. Verified
#: on load: a summary whose notes were edited does not load.
_NOTES: tuple[str, ...] = (
    "each window is an independent simulation: capital resets and no "
    "position carries between segments",
    "selection never sees its own test segment; later train windows do "
    "contain earlier test segments (standard walk-forward - they are "
    "past data by then), so this track is not a single global hold-out",
    "the track compounds each segment's net return as if the full "
    "capital were re-deployed at each segment start",
)


# ---------------------------------------------------------------------------
# Window generation
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class WalkForwardWindow:
    """One train-then-test span of a walk-forward, by bar position.

    Attributes:
        index: Window number, starting at 0, in generation order.
        train_index / train_bars: Training slice position and size.
        train_start / train_end: First and last training bar
            timestamps (inclusive).
        test_index / test_bars: Held-out slice position and size —
            always ``train_index + train_bars`` (the slices are
            adjacent; the test never overlaps its own training data).
        test_start / test_end: First and last test bar timestamps.
    """

    index: int
    train_index: int
    train_bars: int
    train_start: datetime
    train_end: datetime
    test_index: int
    test_bars: int
    test_start: datetime
    test_end: datetime

    def __post_init__(self) -> None:
        if self.index < 0 or self.train_index < 0:
            raise BacktestError("window index and train position are non-negative")
        if self.train_bars < 1 or self.test_bars < 1:
            raise BacktestError(
                "a window carries at least one training and one test bar; got "
                f"train_bars={self.train_bars}, test_bars={self.test_bars}"
            )
        if self.test_index != self.train_index + self.train_bars:
            raise BacktestError(
                "a window's test slice must start exactly where its training "
                f"slice ends (train [{self.train_index}, "
                f"{self.train_index + self.train_bars}), test at "
                f"{self.test_index}): a gap would hide data and an overlap "
                "would leak it"
            )
        if self.train_start > self.train_end:
            raise BacktestError("training span runs backwards")
        if self.train_end >= self.test_start:
            raise BacktestError(
                "the test slice must start strictly after every training bar "
                f"(train ends {self.train_end.isoformat()}, test starts "
                f"{self.test_start.isoformat()}): overlap would leak the "
                "answer into the selection"
            )
        if self.test_start > self.test_end:
            raise BacktestError("test span runs backwards")


def walk_forward_windows(
    data: BacktestData,
    *,
    train: int,
    test: int,
    step: int,
    expanding: bool = False,
) -> tuple[WalkForwardWindow, ...]:
    """Generate the train-then-test windows for a dataset.

    Args:
        data: The pinned dataset; windows are positions in its stored
            chronological order.
        train: Training slice size in bars (rolling windows).
        test: Test slice size in bars.
        step: Bars the window start advances between windows.
        expanding: When true, every window's training slice starts at
            bar 0 and grows with the step (expanding window).

    Returns:
        The windows in index order. At least one always fits, or
        :class:`BacktestError` is raised — a walk-forward that does
        not exist is refused, not reported as empty.

    Raises:
        BacktestError: Non-positive layout numbers, or
            ``train + test`` larger than the dataset.
    """
    if train < 1 or test < 1 or step < 1:
        raise BacktestError(
            f"window layout takes positive bar counts; got train={train}, test={test}, step={step}"
        )
    count = len(data.bars)
    if train + test > count:
        raise BacktestError(
            f"no walk-forward window fits: {count} bars cannot hold "
            f"train={train} + test={test}; refusing to report a "
            "walk-forward that does not exist"
        )
    windows: list[WalkForwardWindow] = []
    index = 0
    while True:
        test_index = index * step + train
        if test_index + test > count:
            break
        train_index = 0 if expanding else index * step
        bars = data.bars
        windows.append(
            WalkForwardWindow(
                index=index,
                train_index=train_index,
                train_bars=test_index - train_index,
                train_start=bars[train_index].timestamp,
                train_end=bars[test_index - 1].timestamp,
                test_index=test_index,
                test_bars=test,
                test_start=bars[test_index].timestamp,
                test_end=bars[test_index + test - 1].timestamp,
            )
        )
        index += 1
    return tuple(windows)


# ---------------------------------------------------------------------------
# One window's outcome
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class WindowOutcome:
    """One window: the selection trace, the test-run numbers, its manifest.

    Attributes:
        window: The span this outcome belongs to.
        selection: Every candidate scored on this window's training
            slice, and the winner.
        out_of_sample: The test slice's numbers, produced by the
            selected candidate alone.
        manifest: The selected test run's §3 manifest.
    """

    window: WalkForwardWindow
    selection: SelectionTrace
    out_of_sample: OutOfSampleNumbers
    manifest: dict[str, object]


def _verify_manifest_bounds(
    where: str, manifest: dict[str, object], *, start: datetime, end: datetime
) -> None:
    """The manifest's recorded simulation period must be this span.

    Every run records its own first/last bars as ``dataset.start`` /
    ``dataset.end`` (manifest.py), so a manifest attached to a window
    but describing different bars is evidence that contradicts its own
    claim — refused rather than left for a reader to reconcile.
    """
    record = _as_mapping(_need(manifest, "dataset", where), f"{where}.dataset")
    for key, want in (("start", start.isoformat()), ("end", end.isoformat())):
        got = _as_text(_need(record, key, f"{where}.dataset"), f"{where}.dataset.{key}")
        if got != want:
            raise BacktestError(
                f"{where} records dataset.{key} {got!r} but its window spans "
                f"{want!r}: evidence that disagrees with the layout it claims to "
                "come from is refused"
            )


# ---------------------------------------------------------------------------
# The aggregated out-of-sample track
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class OosTrack:
    """The out-of-sample segments aggregated, with every part kept visible.

    Attributes:
        windows: Number of test segments (>= 1).
        compounded_net_return: Product of ``1 + segment return`` minus
            1 — the documented full-re-deployment compounding.
        positive / negative / flat: Segment counts by sign (stability
            at a glance: how often the edge showed up at all).
        best_window / worst_window: Indices of the extreme segments
            (first occurrence on ties); the extremes are shown beside
            the aggregate so a single lucky segment cannot hide in an
            average.
        filled: Orders executed across all test segments.
        commission: Fees paid across all test segments.
        round_trips / wins / losses / breakeven: Pooled completed
            cycles under §4's rules.
        hit_rate: ``wins / (wins + losses)`` pooled; ``None`` when no
            cycle completed (nothing to hit).
        wilson_low / wilson_high: Wilson 95% interval for the pooled
            hit rate; ``None`` when there are no trials.
        open_at_end_windows: Segments that ended holding a position —
            their outcome is not in the round-trip counts.
        variants_tried: Total training-slice evaluations across all
            windows — the multiple-testing denominator.
    """

    windows: int
    compounded_net_return: Decimal
    positive: int
    negative: int
    flat: int
    best_window: int
    best_return: Decimal
    worst_window: int
    worst_return: Decimal
    filled: int
    commission: Decimal
    round_trips: int
    wins: int
    losses: int
    breakeven: int
    hit_rate: Decimal | None
    wilson_low: Decimal | None
    wilson_high: Decimal | None
    open_at_end_windows: int
    variants_tried: int


# ---------------------------------------------------------------------------
# The summary
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class WalkForwardSummary:
    """One complete walk-forward, stored the way it can be replayed.

    Attributes:
        dataset_id / dataset_version: The pinned input.
        train_bars / test_bars / step_bars / expanding: The layout
            that generated ``outcomes``.
        objective: The ranking objective's recorded name.
        candidates: Declared labels, in declared order — the race
            every window ran.
        outcomes: One per window, in index order (at least one).
    """

    dataset_id: str
    dataset_version: str
    train_bars: int
    test_bars: int
    step_bars: int
    expanding: bool
    objective: str
    candidates: tuple[str, ...]
    outcomes: tuple[WindowOutcome, ...]

    def __post_init__(self) -> None:
        if not self.candidates:
            raise BacktestError("a walk-forward declares at least one candidate")
        if len(set(self.candidates)) != len(self.candidates):
            raise BacktestError("candidate labels must be distinct to be recordable")
        if not self.objective.strip():
            raise BacktestError("a summary records the objective its windows ranked under")
        if not self.outcomes:
            raise BacktestError("a walk-forward summary carries at least one window")
        for position, outcome in enumerate(self.outcomes):
            if outcome.window.index != position:
                raise BacktestError(
                    "window outcomes must arrive in index order; got "
                    f"position {position} holding index {outcome.window.index}"
                )
            if outcome.selection.objective != self.objective:
                raise BacktestError(
                    f"window {position} ranked under {outcome.selection.objective!r}, "
                    f"the summary records {self.objective!r}"
                )
            raced = tuple(run.label for run in outcome.selection.runs)
            if raced != self.candidates:
                raise BacktestError(
                    f"window {position} raced {raced!r}, but the summary declares "
                    f"{self.candidates!r}: every window must race the same "
                    "declared candidates in the same order"
                )
            # Evidence that disagrees with the layout it claims to come
            # from is refused — in memory as well as from JSON.
            _verify_manifest_bounds(
                f"window {position}'s test manifest",
                outcome.manifest,
                start=outcome.window.test_start,
                end=outcome.window.test_end,
            )
            for run in outcome.selection.runs:
                _verify_manifest_bounds(
                    f"window {position}'s {run.label!r} train manifest",
                    run.manifest,
                    start=outcome.window.train_start,
                    end=outcome.window.train_end,
                )

    @property
    def track(self) -> OosTrack:
        """The out-of-sample segments aggregated from the windows."""
        returns = [outcome.out_of_sample.net_return for outcome in self.outcomes]
        compounded = Decimal(1)
        for value in returns:
            compounded *= Decimal(1) + value
        compounded -= Decimal(1)

        best = max(returns)
        worst = min(returns)
        trials = 0
        wins = 0
        losses = 0
        breakeven = 0
        for outcome in self.outcomes:
            trials += outcome.out_of_sample.wins + outcome.out_of_sample.losses
            wins += outcome.out_of_sample.wins
            losses += outcome.out_of_sample.losses
            breakeven += outcome.out_of_sample.breakeven
        interval = wilson_interval(wins, trials)
        hit_rate = (Decimal(wins) / Decimal(trials)) if trials else None
        return OosTrack(
            windows=len(self.outcomes),
            compounded_net_return=compounded,
            positive=sum(1 for value in returns if value > 0),
            negative=sum(1 for value in returns if value < 0),
            flat=sum(1 for value in returns if value == 0),
            best_window=returns.index(best),
            best_return=best,
            worst_window=returns.index(worst),
            worst_return=worst,
            filled=sum(o.out_of_sample.filled for o in self.outcomes),
            commission=sum((o.out_of_sample.commission for o in self.outcomes), Decimal(0)),
            round_trips=sum(o.out_of_sample.round_trips for o in self.outcomes),
            wins=wins,
            losses=losses,
            breakeven=breakeven,
            hit_rate=hit_rate,
            wilson_low=interval[0] if interval else None,
            wilson_high=interval[1] if interval else None,
            open_at_end_windows=sum(1 for o in self.outcomes if o.out_of_sample.open_at_end),
            variants_tried=len(self.candidates) * len(self.outcomes),
        )

    def to_json(self) -> str:
        """Canonical JSON text for storage (byte-identical across builds)."""
        return _summary_to_json(self)

    @staticmethod
    def from_json(text: str) -> WalkForwardSummary:
        """Parse stored JSON, refusing anything altered or mis-laid-out.

        Raises:
            BacktestError: Not JSON / not an object, wrong ``kind``,
                unknown ``summary_version``, missing or ill-typed
                fields, notes edited away, any embedded manifest whose
                ``run_id`` no longer matches its own payload, or an
                out-of-sample track that does not match the windows it
                claims to summarise.
        """
        return _summary_from_json(text)


def walk_forward(
    data: BacktestData,
    *,
    candidates: Sequence[Candidate],
    config: BacktestConfig,
    risk_factory: Callable[[], RiskEvaluator],
    train: int,
    test: int,
    step: int,
    expanding: bool = False,
    objective: SelectionObjective = ENDING_EQUITY,
) -> WalkForwardSummary:
    """Run a full walk-forward: select inside each window, test after it.

    Args:
        data: The pinned dataset.
        candidates: Declared variants; each run gets a fresh
            instance from its builder and a fresh risk evaluator.
        config: Capital and cost models, identical across all runs.
        risk_factory: Builds one fresh evaluator per run — evaluators
            are per-run objects and must not carry state between
            windows.
        train / test / step: The window layout (see
            :func:`walk_forward_windows`).
        expanding: Expanding instead of rolling training slices.
        objective: The ranking rule, recorded by name.

    Returns:
        The summary: per-window selection traces, out-of-sample
        numbers, every run's manifest, and the aggregated track.

    Raises:
        BacktestError: No candidates, duplicate labels, a layout with
            no window that fits, or a train/test segment shorter than
            the engine's two-bar floor.
    """
    if not candidates:
        raise BacktestError("a walk-forward needs at least one candidate")
    labels = tuple(candidate.label for candidate in candidates)
    if len(set(labels)) != len(labels):
        raise BacktestError(
            "candidate labels must be distinct: the trace names every variant "
            "it tried, and two identical labels cannot be told apart"
        )
    if train < 2 or test < 2:
        raise BacktestError(
            f"the engine decides on one bar and fills on the next, so every "
            f"train and test segment needs at least two bars; got train={train}, "
            f"test={test} (refusing to produce runs the engine cannot perform)"
        )
    by_label = {candidate.label: candidate for candidate in candidates}
    windows = walk_forward_windows(data, train=train, test=test, step=step, expanding=expanding)

    outcomes: list[WindowOutcome] = []
    for window in windows:
        train_slice = data.span(window.train_index, window.train_index + window.train_bars)
        test_slice = data.span(window.test_index, window.test_index + window.test_bars)
        trace = select_on_train(
            train_slice,
            candidates=candidates,
            config=config,
            risk_factory=risk_factory,
            objective=objective,
        )
        risk = risk_factory()
        strategy = by_label[trace.selected].fresh()
        result = run_backtest(test_slice, strategy, config, risk=risk)
        manifest = build_manifest(result, config=config, risk=risk)
        outcomes.append(
            WindowOutcome(
                window=window,
                selection=trace,
                out_of_sample=OutOfSampleNumbers.from_result(result),
                manifest=manifest,
            )
        )

    return WalkForwardSummary(
        dataset_id=data.dataset_id,
        dataset_version=data.version,
        train_bars=train,
        test_bars=test,
        step_bars=step,
        expanding=expanding,
        objective=objective.name,
        candidates=labels,
        outcomes=tuple(outcomes),
    )


def replay_walk_forward(
    root: Path,
    summary: WalkForwardSummary,
    *,
    builders: Mapping[str, Candidate],
    risk_factory: Callable[[], RiskEvaluator],
    objective: SelectionObjective = ENDING_EQUITY,
) -> tuple[BacktestResult, ...]:
    """Re-execute every manifest in a summary and re-derive its numbers.

    The stored evidence is worthless if nobody can run it again, so
    replay verifies, failing closed at the first mismatch:

    1. The caller's objective is the one the summary ranked under —
       scores cannot be re-derived under a different rule.
    2. Every declared candidate has a builder (the manifest proves the
       built strategy is the one that ran, field for field).
    3. Every manifest reproduces byte-for-byte: the pinned dataset is
       loaded, narrowed to the recorded window (exact bounds), run,
       and compared artefact by artefact
       (:func:`~harsh_quant_os.backtesting.manifest.run_from_manifest`).
    4. Every selection score re-derives from the reproduced run.
    5. Every window's out-of-sample numbers re-derive from the
       reproduced test run, exactly.

    Args:
        root: The data root holding ``clean/``.
        summary: The walk-forward summary (fresh or loaded from JSON).
        builders: ``label -> candidate`` for every declared candidate;
            builders for labels the summary does not declare are
            ignored.
        risk_factory: A **fresh** evaluator per run.
        objective: The ranking objective, matching the summary's.

    Returns:
        The reproduced out-of-sample results, one per window in index
        order.

    Raises:
        BacktestError: Objective mismatch, missing builder, a manifest
            that does not reproduce, a score that does not re-derive,
            or numbers that do not follow from their manifest.
        RecipeError: A pinned dataset version is absent or its stored
            hash no longer matches.
        ReproductionMismatch: A run executed but produced different
            artefacts.
    """
    if summary.objective != objective.name:
        raise BacktestError(
            f"the summary ranked under {summary.objective!r} but replay was "
            f"given objective {objective.name!r}: scores cannot be re-derived "
            "under a different rule than the one recorded"
        )
    missing = [label for label in summary.candidates if label not in builders]
    if missing:
        raise BacktestError(
            "no builder supplied for candidate(s) "
            + ", ".join(repr(label) for label in missing)
            + ": a run whose strategy cannot be rebuilt cannot be replayed"
        )

    replayed: list[BacktestResult] = []
    for outcome in summary.outcomes:
        index = outcome.window.index
        for run in outcome.selection.runs:
            result = run_from_manifest(
                root,
                run.manifest,
                strategy=builders[run.label].fresh(),
                risk=risk_factory(),
            )
            score = objective(result)
            if score != run.score:
                raise BacktestError(
                    f"window {index}: candidate {run.label!r} scored {run.score} "
                    f"in the summary but {score} on replay — the stored score "
                    "does not follow from the stored manifest"
                )
        test_result = run_from_manifest(
            root,
            outcome.manifest,
            strategy=builders[outcome.selection.selected].fresh(),
            risk=risk_factory(),
        )
        numbers = OutOfSampleNumbers.from_result(test_result)
        if numbers != outcome.out_of_sample:
            raise BacktestError(
                f"window {index}: out-of-sample numbers did not reproduce "
                f"(summary: {outcome.out_of_sample}, replay: {numbers}) — the "
                "stored evidence does not follow from the stored manifest"
            )
        replayed.append(test_result)
    return tuple(replayed)


# ---------------------------------------------------------------------------
# Canonical JSON (evidence that can be loaded, checked and replayed)
# ---------------------------------------------------------------------------


def _canonical(payload: object) -> str:
    # Same canonical form as manifest_to_json: byte-identical across
    # builds, keys sorted, ASCII only.
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True)


def _need(mapping: dict[str, object], key: str, where: str) -> object:
    if key not in mapping:
        raise BacktestError(f"walk-forward summary is missing {where}.{key}")
    return mapping[key]


def _as_text(value: object, where: str) -> str:
    if not isinstance(value, str):
        raise BacktestError(f"{where} must be a string, got {type(value).__name__}")
    return value


def _as_int(value: object, where: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise BacktestError(f"{where} must be an integer, got {type(value).__name__}")
    return value


def _as_bool(value: object, where: str) -> bool:
    if not isinstance(value, bool):
        raise BacktestError(f"{where} must be true or false, got {type(value).__name__}")
    return value


def _as_decimal(value: object, where: str) -> Decimal:
    text = _as_text(value, where)
    try:
        parsed = Decimal(text)
    except (InvalidOperation, ValueError) as error:
        raise BacktestError(f"{where} is not a decimal number: {text!r}") from error
    if not parsed.is_finite():
        raise BacktestError(f"{where} must be finite, got {text!r}")
    return parsed


def _as_time(value: object, where: str) -> datetime:
    text = _as_text(value, where)
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError as error:
        raise BacktestError(f"{where} is not an ISO timestamp: {text!r}") from error
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        raise BacktestError(
            f"{where} must be timezone-aware (the engine's bar timestamps are): got {text!r}"
        )
    return parsed


def _as_mapping(value: object, where: str) -> dict[str, object]:
    if not isinstance(value, dict):
        raise BacktestError(f"{where} must be a JSON object, got {type(value).__name__}")
    return cast(dict[str, object], value)


def _as_list(value: object, where: str) -> list[object]:
    if not isinstance(value, list):
        raise BacktestError(f"{where} must be a JSON array, got {type(value).__name__}")
    return value


def _window_from(mapping: dict[str, object], where: str) -> WalkForwardWindow:
    train = _as_mapping(_need(mapping, "train", where), f"{where}.train")
    test = _as_mapping(_need(mapping, "test", where), f"{where}.test")
    return WalkForwardWindow(
        index=_as_int(_need(mapping, "index", where), f"{where}.index"),
        train_index=_as_int(_need(mapping, "train_index", where), f"{where}.train_index"),
        train_bars=_as_int(_need(train, "bars", f"{where}.train"), f"{where}.train.bars"),
        train_start=_as_time(_need(train, "start", f"{where}.train"), f"{where}.train.start"),
        train_end=_as_time(_need(train, "end", f"{where}.train"), f"{where}.train.end"),
        test_index=_as_int(_need(mapping, "test_index", where), f"{where}.test_index"),
        test_bars=_as_int(_need(test, "bars", f"{where}.test"), f"{where}.test.bars"),
        test_start=_as_time(_need(test, "start", f"{where}.test"), f"{where}.test.start"),
        test_end=_as_time(_need(test, "end", f"{where}.test"), f"{where}.test.end"),
    )


def _numbers_from(mapping: dict[str, object], where: str) -> OutOfSampleNumbers:
    return OutOfSampleNumbers(
        net_return=_as_decimal(_need(mapping, "net_return", where), f"{where}.net_return"),
        ending_equity=_as_decimal(_need(mapping, "ending_equity", where), f"{where}.ending_equity"),
        filled=_as_int(_need(mapping, "filled", where), f"{where}.filled"),
        round_trips=_as_int(_need(mapping, "round_trips", where), f"{where}.round_trips"),
        wins=_as_int(_need(mapping, "wins", where), f"{where}.wins"),
        losses=_as_int(_need(mapping, "losses", where), f"{where}.losses"),
        breakeven=_as_int(_need(mapping, "breakeven", where), f"{where}.breakeven"),
        open_at_end=_as_bool(_need(mapping, "open_at_end", where), f"{where}.open_at_end"),
        commission=_as_decimal(_need(mapping, "commission", where), f"{where}.commission"),
    )


def _selection_from(mapping: dict[str, object], where: str) -> SelectionTrace:
    runs_raw = _as_list(_need(mapping, "train_runs", where), f"{where}.train_runs")
    runs: list[CandidateRun] = []
    for position, entry in enumerate(runs_raw):
        entry_where = f"{where}.train_runs[{position}]"
        run = _as_mapping(entry, entry_where)
        manifest = _as_mapping(_need(run, "manifest", entry_where), f"{entry_where}.manifest")
        recorded = manifest.get("run_id")
        if recorded is None or compute_run_id(manifest) != _as_text(
            recorded, f"{entry_where}.manifest.run_id"
        ):
            raise BacktestError(
                f"{entry_where}: manifest run_id does not match its own payload "
                "(the summary has been altered since it was written)"
            )
        runs.append(
            CandidateRun(
                label=_as_text(_need(run, "label", entry_where), f"{entry_where}.label"),
                score=_as_decimal(_need(run, "score", entry_where), f"{entry_where}.score"),
                manifest=manifest,
            )
        )
    tied = tuple(
        _as_text(entry, f"{where}.tied[{position}]")
        for position, entry in enumerate(_as_list(_need(mapping, "tied", where), f"{where}.tied"))
    )
    return SelectionTrace(
        selected=_as_text(_need(mapping, "selected", where), f"{where}.selected"),
        tied=tied,
        objective=_as_text(_need(mapping, "objective", where), f"{where}.objective"),
        runs=tuple(runs),
    )


def _outcome_from(mapping: dict[str, object], where: str) -> WindowOutcome:
    manifest = _as_mapping(_need(mapping, "manifest", where), f"{where}.manifest")
    recorded = manifest.get("run_id")
    if recorded is None or compute_run_id(manifest) != _as_text(
        recorded, f"{where}.manifest.run_id"
    ):
        raise BacktestError(
            f"{where}.manifest: run_id does not match its own payload "
            "(the summary has been altered since it was written)"
        )
    return WindowOutcome(
        window=_window_from(
            _as_mapping(_need(mapping, "window", where), f"{where}.window"),
            f"{where}.window",
        ),
        selection=_selection_from(
            _as_mapping(_need(mapping, "selection", where), f"{where}.selection"),
            f"{where}.selection",
        ),
        out_of_sample=_numbers_from(
            _as_mapping(_need(mapping, "out_of_sample", where), f"{where}.out_of_sample"),
            f"{where}.out_of_sample",
        ),
        manifest=manifest,
    )


def _track_from(mapping: dict[str, object], where: str) -> OosTrack:
    best = _as_mapping(_need(mapping, "best", where), f"{where}.best")
    worst = _as_mapping(_need(mapping, "worst", where), f"{where}.worst")
    hit_rate_raw = _need(mapping, "hit_rate", where)
    wilson_raw = _need(mapping, "wilson_95", where)
    hit_rate = None if hit_rate_raw is None else _as_decimal(hit_rate_raw, f"{where}.hit_rate")
    if wilson_raw is None:
        wilson: tuple[Decimal, Decimal] | None = None
    else:
        bounds = _as_list(wilson_raw, f"{where}.wilson_95")
        if len(bounds) != 2:
            raise BacktestError(
                f"{where}.wilson_95 must hold exactly two bounds, got {len(bounds)}"
            )
        wilson = (
            _as_decimal(bounds[0], f"{where}.wilson_95[0]"),
            _as_decimal(bounds[1], f"{where}.wilson_95[1]"),
        )
    return OosTrack(
        windows=_as_int(_need(mapping, "windows", where), f"{where}.windows"),
        compounded_net_return=_as_decimal(
            _need(mapping, "compounded_net_return", where),
            f"{where}.compounded_net_return",
        ),
        positive=_as_int(_need(mapping, "positive", where), f"{where}.positive"),
        negative=_as_int(_need(mapping, "negative", where), f"{where}.negative"),
        flat=_as_int(_need(mapping, "flat", where), f"{where}.flat"),
        best_window=_as_int(_need(best, "window", f"{where}.best"), f"{where}.best.window"),
        best_return=_as_decimal(_need(best, "return", f"{where}.best"), f"{where}.best.return"),
        worst_window=_as_int(_need(worst, "window", f"{where}.worst"), f"{where}.worst.window"),
        worst_return=_as_decimal(_need(worst, "return", f"{where}.worst"), f"{where}.worst.return"),
        filled=_as_int(_need(mapping, "filled", where), f"{where}.filled"),
        commission=_as_decimal(_need(mapping, "commission", where), f"{where}.commission"),
        round_trips=_as_int(_need(mapping, "round_trips", where), f"{where}.round_trips"),
        wins=_as_int(_need(mapping, "wins", where), f"{where}.wins"),
        losses=_as_int(_need(mapping, "losses", where), f"{where}.losses"),
        breakeven=_as_int(_need(mapping, "breakeven", where), f"{where}.breakeven"),
        hit_rate=hit_rate,
        wilson_low=None if wilson is None else wilson[0],
        wilson_high=None if wilson is None else wilson[1],
        open_at_end_windows=_as_int(
            _need(mapping, "open_at_end_windows", where), f"{where}.open_at_end_windows"
        ),
        variants_tried=_as_int(_need(mapping, "variants_tried", where), f"{where}.variants_tried"),
    )


def _track_payload(track: OosTrack) -> dict[str, object]:
    hit_rate: object = None if track.hit_rate is None else str(track.hit_rate)
    wilson: object = (
        None
        if track.wilson_low is None or track.wilson_high is None
        else [str(track.wilson_low), str(track.wilson_high)]
    )
    return {
        "windows": track.windows,
        "compounded_net_return": str(track.compounded_net_return),
        "positive": track.positive,
        "negative": track.negative,
        "flat": track.flat,
        "best": {"window": track.best_window, "return": str(track.best_return)},
        "worst": {"window": track.worst_window, "return": str(track.worst_return)},
        "filled": track.filled,
        "commission": str(track.commission),
        "round_trips": track.round_trips,
        "wins": track.wins,
        "losses": track.losses,
        "breakeven": track.breakeven,
        "hit_rate": hit_rate,
        "wilson_95": wilson,
        "open_at_end_windows": track.open_at_end_windows,
        "variants_tried": track.variants_tried,
    }


def _numbers_payload(numbers: OutOfSampleNumbers) -> dict[str, object]:
    return {
        "net_return": str(numbers.net_return),
        "ending_equity": str(numbers.ending_equity),
        "filled": numbers.filled,
        "round_trips": numbers.round_trips,
        "wins": numbers.wins,
        "losses": numbers.losses,
        "breakeven": numbers.breakeven,
        "open_at_end": numbers.open_at_end,
        "commission": str(numbers.commission),
    }


def _time_payload(value: datetime) -> str:
    return value.isoformat()


# Attach the JSON surface to the summary (kept beside the class so the
# dataclass above stays a plain record).
def _summary_to_json(summary: WalkForwardSummary) -> str:
    windows: list[object] = []
    for outcome in summary.outcomes:
        window = outcome.window
        trace = outcome.selection
        windows.append(
            {
                "window": {
                    "index": window.index,
                    "train_index": window.train_index,
                    "test_index": window.test_index,
                    "train": {
                        "start": _time_payload(window.train_start),
                        "end": _time_payload(window.train_end),
                        "bars": window.train_bars,
                    },
                    "test": {
                        "start": _time_payload(window.test_start),
                        "end": _time_payload(window.test_end),
                        "bars": window.test_bars,
                    },
                },
                "selection": {
                    "selected": trace.selected,
                    "tied": list(trace.tied),
                    "objective": trace.objective,
                    "train_runs": [
                        {
                            "label": run.label,
                            "score": str(run.score),
                            "manifest": run.manifest,
                        }
                        for run in trace.runs
                    ],
                },
                "out_of_sample": _numbers_payload(outcome.out_of_sample),
                "manifest": outcome.manifest,
            }
        )
    payload: dict[str, object] = {
        "kind": "walk_forward",
        "summary_version": SUMMARY_VERSION,
        "dataset": {"id": summary.dataset_id, "version": summary.dataset_version},
        "layout": {
            "train_bars": summary.train_bars,
            "test_bars": summary.test_bars,
            "step_bars": summary.step_bars,
            "expanding": summary.expanding,
        },
        "objective": summary.objective,
        "candidates": list(summary.candidates),
        "notes": list(_NOTES),
        "windows": windows,
        "out_of_sample_track": _track_payload(summary.track),
    }
    return _canonical(payload)


def _summary_from_json(text: str) -> WalkForwardSummary:
    try:
        parsed: object = json.loads(text)
    except ValueError as error:
        raise BacktestError(f"walk-forward summary is not valid JSON: {error}") from error
    root = _as_mapping(parsed, "walk-forward summary")
    kind = _as_text(_need(root, "kind", "summary"), "summary.kind")
    if kind != "walk_forward":
        raise BacktestError(
            f"not a walk-forward summary (kind={kind!r}); refusing to read it as one"
        )
    version = _as_int(_need(root, "summary_version", "summary"), "summary.summary_version")
    if version != SUMMARY_VERSION:
        raise BacktestError(
            f"summary_version {version} is not what this build understands "
            f"({SUMMARY_VERSION}); refusing to guess its layout"
        )
    dataset = _as_mapping(_need(root, "dataset", "summary"), "summary.dataset")
    layout = _as_mapping(_need(root, "layout", "summary"), "summary.layout")

    stored_notes = tuple(
        _as_text(entry, f"summary.notes[{position}]")
        for position, entry in enumerate(_as_list(_need(root, "notes", "summary"), "summary.notes"))
    )
    if stored_notes != _NOTES:
        raise BacktestError(
            "the summary's honesty notes do not match this build's: the file "
            "has been altered or written by another version"
        )

    candidates = tuple(
        _as_text(entry, f"summary.candidates[{position}]")
        for position, entry in enumerate(
            _as_list(_need(root, "candidates", "summary"), "summary.candidates")
        )
    )
    outcomes = tuple(
        _outcome_from(
            _as_mapping(entry, f"summary.windows[{position}]"),
            f"summary.windows[{position}]",
        )
        for position, entry in enumerate(
            _as_list(_need(root, "windows", "summary"), "summary.windows")
        )
    )
    summary = WalkForwardSummary(
        dataset_id=_as_text(_need(dataset, "id", "summary.dataset"), "summary.dataset.id"),
        dataset_version=_as_text(
            _need(dataset, "version", "summary.dataset"), "summary.dataset.version"
        ),
        train_bars=_as_int(
            _need(layout, "train_bars", "summary.layout"), "summary.layout.train_bars"
        ),
        test_bars=_as_int(_need(layout, "test_bars", "summary.layout"), "summary.layout.test_bars"),
        step_bars=_as_int(_need(layout, "step_bars", "summary.layout"), "summary.layout.step_bars"),
        expanding=_as_bool(
            _need(layout, "expanding", "summary.layout"), "summary.layout.expanding"
        ),
        objective=_as_text(_need(root, "objective", "summary"), "summary.objective"),
        candidates=candidates,
        outcomes=outcomes,
    )

    # The aggregate must equal what the windows it claims to
    # summarise actually produce — a tampered track is a lie, not a
    # formatting choice.
    stored_track = _track_from(
        _as_mapping(_need(root, "out_of_sample_track", "summary"), "summary.out_of_sample_track"),
        "summary.out_of_sample_track",
    )
    if stored_track != summary.track:
        raise BacktestError(
            "out_of_sample_track does not match the windows it summarises "
            "(the summary has been altered since it was written)"
        )
    return summary
