"""phase 2 research schema: datasets, provenance, strategies, experiments, journal

Revision ID: 3842df3d0db8
Revises: 930c38609bc3
Create Date: 2026-09-29 10:51:40.988177

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3842df3d0db8"
down_revision: str | None = "930c38609bc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datasets",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(name) > 0", name=op.f("ck_datasets_name_present")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_datasets_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_datasets")),
        sa.UniqueConstraint("name", name=op.f("uq_datasets_name")),
    )
    op.create_table(
        "strategies",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "spec",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(name) > 0", name=op.f("ck_strategies_name_present")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_strategies_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategies")),
        sa.UniqueConstraint("name", name=op.f("uq_strategies_name")),
    )
    op.create_table(
        "dataset_provenance",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column(
            "acquired_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("checksum_sha256", sa.Text(), nullable=True),
        sa.Column("row_count", sa.BigInteger(), nullable=True),
        sa.Column("license", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(source) > 0", name=op.f("ck_dataset_provenance_source_present")),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_dataset_provenance_dataset_id_datasets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_provenance")),
    )
    op.create_index(
        op.f("ix_dataset_provenance_dataset_id"), "dataset_provenance", ["dataset_id"], unique=False
    )
    op.create_table(
        "experiments",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("strategy_id", sa.Uuid(), nullable=True),
        sa.Column("dataset_id", sa.Uuid(), nullable=True),
        sa.Column(
            "parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default=sa.text("'planned'"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('planned', 'running', 'completed', 'failed')",
            name=op.f("ck_experiments_status_known"),
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR started_at IS NOT NULL",
            name=op.f("ck_experiments_finished_requires_start"),
        ),
        sa.CheckConstraint("length(name) > 0", name=op.f("ck_experiments_name_present")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_experiments_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_experiments_dataset_id_datasets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
            name=op.f("fk_experiments_strategy_id_strategies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiments")),
    )
    op.create_index(op.f("ix_experiments_dataset_id"), "experiments", ["dataset_id"], unique=False)
    op.create_index(
        op.f("ix_experiments_strategy_id"), "experiments", ["strategy_id"], unique=False
    )
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("experiment_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(body) > 0", name=op.f("ck_journal_entries_body_present")),
        sa.CheckConstraint("length(title) > 0", name=op.f("ck_journal_entries_title_present")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_journal_entries_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
            name=op.f("fk_journal_entries_experiment_id_experiments"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entries")),
    )
    op.create_index(
        op.f("ix_journal_entries_experiment_id"), "journal_entries", ["experiment_id"], unique=False
    )
    # --- append-only provenance -------------------------------------
    # Autogenerate cannot express triggers, so this is written by hand,
    # the same way `audit_log`'s is in the previous revision, and for the
    # same reason: a before-trigger runs regardless of the caller's
    # privileges, so it holds even for a role that could bypass table
    # ACLs. Provenance is a claim about where data came from; a claim that
    # can be edited later is not provenance. Corrections are appended as
    # new rows, which is also what actually happened.
    #
    # This also means `dataset_provenance` cannot be deleted by a cascade:
    # DROP TABLE does not fire row triggers, so dropping the *table* still
    # works - it is row-by-row DELETE that is refused.
    op.execute(
        sa.text(
            "CREATE FUNCTION hqos_dataset_provenance_immutable() RETURNS trigger AS $hqos$ "
            "BEGIN "
            "RAISE EXCEPTION "
            "'dataset_provenance is append-only: % is not permitted', TG_OP "
            "USING ERRCODE = '42501'; "
            "END; "
            "$hqos$ LANGUAGE plpgsql"
        )
    )
    op.execute(
        sa.text(
            "CREATE TRIGGER dataset_provenance_append_only "
            "BEFORE UPDATE OR DELETE ON dataset_provenance "
            "FOR EACH ROW EXECUTE FUNCTION hqos_dataset_provenance_immutable()"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this revision.

    Every revision in this repository is expected to be reversible: the
    Phase 2 exit criteria require migrations to run from empty to current
    and back.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_journal_entries_experiment_id"), table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_index(op.f("ix_experiments_strategy_id"), table_name="experiments")
    op.drop_index(op.f("ix_experiments_dataset_id"), table_name="experiments")
    op.drop_table("experiments")
    op.drop_index(op.f("ix_dataset_provenance_dataset_id"), table_name="dataset_provenance")
    op.drop_table("dataset_provenance")
    op.drop_table("strategies")
    op.drop_table("datasets")
    # ### end Alembic commands ###
    # Table drops do not remove the trigger *function* - PostgreSQL keeps
    # it once no table references it - so it is dropped explicitly, after
    # the table that used it is gone.
    op.execute(sa.text("DROP FUNCTION IF EXISTS hqos_dataset_provenance_immutable()"))
