"""phase 2 identity, sessions and append-only audit log

Revision ID: 930c38609bc3
Revises:
Create Date: 2026-09-28 22:46:40.281483

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "930c38609bc3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_email", sa.Text(), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "event_type IN ('user.created', 'auth.login.succeeded', 'auth.login.failed', 'auth.logout.succeeded', 'auth.session.revoked', 'auth.session.rejected')",
            name=op.f("ck_audit_log_event_type"),
        ),
        sa.CheckConstraint("outcome IN ('success', 'failure')", name=op.f("ck_audit_log_outcome")),
        sa.CheckConstraint(
            "actor_email IS NULL OR actor_email = lower(actor_email)",
            name=op.f("ck_audit_log_actor_email_lowercase"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_occurred_at"), "audit_log", ["occurred_at"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
        sa.CheckConstraint(
            "length(password_hash) > 0", name=op.f("ck_users_password_hash_present")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_index(op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    # --- append-only enforcement -------------------------------------
    # Autogenerate cannot express triggers, so this is written by hand.
    # database.md section 4 requires that audit rows be immutable and that
    # "the application role cannot modify audit rows". The local role is a
    # superuser, which PostgreSQL lets bypass table ACLs, so a REVOKE would
    # be decorative here - the trigger is the control that actually holds,
    # because a BEFORE trigger runs regardless of the caller's privileges.
    # SQLSTATE 42501 (insufficient_privilege) is used so the refusal reads as
    # a permission problem rather than as a constraint the caller could fix.
    op.execute(
        sa.text(
            "CREATE FUNCTION hqos_audit_log_immutable() RETURNS trigger AS $hqos$ "
            "BEGIN "
            "RAISE EXCEPTION "
            "'audit_log is append-only: % is not permitted', TG_OP "
            "USING ERRCODE = '42501'; "
            "END; "
            "$hqos$ LANGUAGE plpgsql"
        )
    )
    op.execute(
        sa.text(
            "CREATE TRIGGER audit_log_append_only "
            "BEFORE UPDATE OR DELETE ON audit_log "
            "FOR EACH ROW EXECUTE FUNCTION hqos_audit_log_immutable()"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this revision.

    Every revision in this repository is expected to be reversible: the
    Phase 2 exit criteria require migrations to run from empty to current
    and back.
    """
    # Order matters: dropping the table removes its trigger, after which the
    # trigger *function* is orphaned - PostgreSQL does not drop a function
    # when the last table using it goes away. Dropping the table first also
    # sidesteps the trigger, since DROP TABLE does not fire row triggers.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("users")
    op.drop_index(op.f("ix_audit_log_occurred_at"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
    op.execute(sa.text("DROP FUNCTION IF EXISTS hqos_audit_log_immutable()"))
